name: Package Dist Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag
        required: true
        default: latest
        type: choice
        options:
        - latest
        - beta

jobs:
  dist-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup registry
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org/

    - name: Publish package
      run: |
        version=$(npm run env | grep npm_package_version | cut -d = -f 2)
        npm dist-tag add @resconet/jsbridge@$version ${{ inputs.tag }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
